
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "ExtThemeNeptune": "packages/ext-theme-neptune/overrides",
  "Ext": "ext/src",
  "BASECAMP": "app",
  "Ext.rtl.EventObjectImpl": "ext/src/rtl/EventObject.js",
  "Overrides": "lib/overrides",
  "Abstract": "lib/abstract"
});
Ext.ClassManager.addNameAlternateMappings({
  "ExtThemeNeptune.container.ButtonGroup": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "BASECAMP.view.todolists.UI": [],
  "ExtThemeNeptune.toolbar.Paging": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "BASECAMP.view.todolists.Window": [],
  "BASECAMP.store.Todos": [],
  "Ext.ux.CheckColumn": [],
  "Ext.ux.PreviewPlugin": [],
  "BASECAMP.view.documents.UI": [],
  "BASECAMP.view.documents.Grid": [],
  "Ext.ux.ajax.SimXhr": [],
  "BASECAMP.view.uploads.Grid": [],
  "Ext.ux.event.RecorderManager": [],
  "BASECAMP.store.Uploads": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Overrides.data.reader.Reader": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "BASECAMP.view.uploads.UI": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "BASECAMP.store.TodoLists": [],
  "Ext.ux.event.Recorder": [],
  "BASECAMP.model.User": [],
  "BASECAMP.view.topics.Grid": [],
  "BASECAMP.controller.Uploads": [],
  "BASECAMP.model.Upload": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "BASECAMP.view.topics.UI": [],
  "Ext.ux.TabScrollerMenu": [],
  "ExtThemeNeptune.menu.Separator": [],
  "Ext.ux.IFrame": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "ExtThemeNeptune.grid.RowEditor": [],
  "ExtThemeNeptune.picker.Month": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "BASECAMP.model.Project": [],
  "Ext.ux.BoxReorderer": [],
  "ExtThemeNeptune.menu.Menu": [],
  "BASECAMP.model.Topic": [],
  "BASECAMP.model.Todo": [],
  "Ext.ux.grid.filter.Filter": [],
  "BASECAMP.view.Viewport": [],
  "Ext.ux.GroupTabRenderer": [],
  "BASECAMP.controller.Projects": [],
  "BASECAMP.view.topics.Window": [],
  "BASECAMP.controller.Documents": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "ExtThemeNeptune.panel.Panel": [],
  "BASECAMP.model.Name": [],
  "BASECAMP.model.TodoList": [],
  "ExtThemeNeptune.toolbar.Toolbar": [],
  "ExtThemeNeptune.tab.Tab": [],
  "Ext.ux.GMapPanel": [],
  "BASECAMP.view.project.UI": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [],
  "Abstract.controller.Navigation": [],
  "BASECAMP.store.Projects": [],
  "BASECAMP.view.todolists.Grid": [],
  "Ext.ux.DataView.Animated": [],
  "ExtThemeNeptune.resizer.Splitter": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "BASECAMP.store.Topics": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "BASECAMP.view.project.Selector": [],
  "Ext.ux.event.Player": [],
  "BASECAMP.controller.Login": [],
  "BASECAMP.view.todos.Grid": [],
  "BASECAMP.controller.Navigation": [],
  "BASECAMP.view.Login": [],
  "ExtThemeNeptune.panel.Tool": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "BASECAMP.controller.TodoLists": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [],
  "BASECAMP.controller.Main": [],
  "BASECAMP.model.Document": [],
  "BASECAMP.store.Documents": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "ExtThemeNeptune.form.field.HtmlEditor": [],
  "Ext.ux.grid.FiltersFeature": [],
  "BASECAMP.controller.Topics": []
});
Ext.ClassManager.addNameAliasMappings({
  "ExtThemeNeptune.container.ButtonGroup": [],
  "Ext.ux.grid.TransformGrid": [],
  "Ext.ux.ajax.DataSimlet": [],
  "BASECAMP.view.todolists.UI": [
    "widget.todolists"
  ],
  "ExtThemeNeptune.toolbar.Paging": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.DataView.DragSelector": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "BASECAMP.view.todolists.Window": [
    "widget.todolistmodal"
  ],
  "BASECAMP.store.Todos": [],
  "Ext.ux.CheckColumn": [
    "widget.checkcolumn"
  ],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "BASECAMP.view.documents.UI": [
    "widget.documents"
  ],
  "BASECAMP.view.documents.Grid": [
    "widget.documentsgrid"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "BASECAMP.view.uploads.Grid": [
    "widget.uploadsgrid"
  ],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "BASECAMP.store.Uploads": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Overrides.data.reader.Reader": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "BASECAMP.view.uploads.UI": [
    "widget.uploads"
  ],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "BASECAMP.store.TodoLists": [],
  "Ext.ux.event.Recorder": [],
  "BASECAMP.model.User": [],
  "BASECAMP.view.topics.Grid": [
    "widget.topicsgrid"
  ],
  "BASECAMP.controller.Uploads": [],
  "BASECAMP.model.Upload": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "BASECAMP.view.topics.UI": [
    "widget.topics"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "ExtThemeNeptune.menu.Separator": [],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "ExtThemeNeptune.grid.RowEditor": [],
  "ExtThemeNeptune.picker.Month": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "BASECAMP.model.Project": [],
  "Ext.ux.BoxReorderer": [],
  "ExtThemeNeptune.menu.Menu": [],
  "BASECAMP.model.Topic": [],
  "BASECAMP.model.Todo": [],
  "Ext.ux.grid.filter.Filter": [],
  "BASECAMP.view.Viewport": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "BASECAMP.controller.Projects": [],
  "BASECAMP.view.topics.Window": [
    "widget.topicsmodal"
  ],
  "BASECAMP.controller.Documents": [],
  "Ext.ux.FieldReplicator": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "ExtThemeNeptune.panel.Panel": [],
  "BASECAMP.model.Name": [],
  "BASECAMP.model.TodoList": [],
  "ExtThemeNeptune.toolbar.Toolbar": [],
  "ExtThemeNeptune.tab.Tab": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "BASECAMP.view.project.UI": [
    "widget.projectpanel"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Abstract.controller.Navigation": [],
  "BASECAMP.store.Projects": [],
  "BASECAMP.view.todolists.Grid": [
    "widget.todolistgrid"
  ],
  "Ext.ux.DataView.Animated": [],
  "ExtThemeNeptune.resizer.Splitter": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "BASECAMP.store.Topics": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "BASECAMP.view.project.Selector": [
    "widget.projectselector"
  ],
  "Ext.ux.event.Player": [],
  "BASECAMP.controller.Login": [],
  "BASECAMP.view.todos.Grid": [
    "widget.todogrid"
  ],
  "BASECAMP.controller.Navigation": [],
  "BASECAMP.view.Login": [
    "widget.login"
  ],
  "ExtThemeNeptune.panel.Tool": [],
  "Ext.ux.ToolbarDroppable": [],
  "Ext.ux.event.Maker": [],
  "BASECAMP.controller.TodoLists": [],
  "Ext.ux.DataView.Draggable": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "BASECAMP.controller.Main": [],
  "BASECAMP.model.Document": [],
  "BASECAMP.store.Documents": [],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "ExtThemeNeptune.form.field.HtmlEditor": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "BASECAMP.controller.Topics": []
});
